[tool.poetry]
name = "email"
version = "0.1.0"
description = ""
authors = ["John Maximilian <2e0byo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
msal = "^1.17.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
